/*******************************************************************************
 * Copyright (c) 2002-2016 "Marco Aurelio Barbosa Fagnani Gomes Lotz"
 * [http://www.marcolotz.com]
 *
 * This file is part of Marco Lotz Hadoop Lung solution.
 *
 * Hadoop Lung is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

package com.marcolotz.lung.mapreduce.mapper;

import ij.plugin.DICOM;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.apache.hadoop.io.BytesWritable;
import org.apache.hadoop.io.NullWritable;
import org.apache.hadoop.mapreduce.Mapper;

import com.marcolotz.imageprocess.GrayNoduleCandidates;
import com.marcolotz.imageprocess.ImageProcessor;
import com.marcolotz.imageprocess.NullPreProcessor;
import com.marcolotz.imageprocess.TresholdLung;
import com.marcolotz.lung.mapreduce.MRComponents.KeyStructureWritable;
import com.marcolotz.lung.mapreduce.MapperComponents.ImageMetadata;
import com.marcolotz.lung.mapreduce.MapperComponents.ImageStructure;
import com.marcolotz.lung.mapreduce.io.inputFormat.DistributedDicomReader;

/**
 * Mapper used in the HadoopLung application. All the images are processed in
 * the Map phase.
 * 
 * @author Marco Aurelio Lotz
 * 
 */
public class LungMapper
		extends
		Mapper<NullWritable, BytesWritable, KeyStructureWritable, ImageMetadata> {

	// private static final Log LOG = LogFactory.getLog(LungMapper.class);

	/***
	 * The key generated by the record reader is a NullWritable with no content.
	 * The value is a byte array that represents a DICOM image.
	 * 
	 * @param nothing
	 * @param dicomImage
	 * @param context
	 * @throws IOException
	 * @throws InterruptedException
	 */
	@Override
	protected void map(NullWritable nothing, BytesWritable dicomImage,
			Context context) throws IOException, InterruptedException {

		/***
		 * Local Attributes declarations
		 */
		DistributedDicomReader reader;
		ImageProcessor imageProcessor;

		KeyStructureWritable keyStructure;
		ImageStructure imageStructure;
		ImageMetadata imageMetadata;

		// Generates a DICOM image from the BytesWritable input.
		DICOM image = convertToDICOM(dicomImage);

		// Process image meta information
		// generating a key-value pair for the image
		reader = new DistributedDicomReader(image);

		// Gets the key from the reader.
		keyStructure = reader.getKeyStructure();

		// Gets the image meta data from the reader
		imageStructure = reader.getImageStructure();

		/***
		 * Process the DICOM image: inside the image processor one can use
		 * plugins.
		 */
		imageProcessor = new ImageProcessor(NullPreProcessor.class,
				TresholdLung.class, GrayNoduleCandidates.class,
				context.getConfiguration());
		imageProcessor.setInput(image);
		imageProcessor.run();

		/***
		 * Updates the imageStructure with the nodes detected by the @imageProcessor
		 */
		imageStructure
				.setNodeCandidatesList(imageProcessor.getNodeCandidates());

		/***
		 * Generates the emitted value. The value has Metadata from the image
		 * Structure, including image information and blob data.
		 */
		imageMetadata = new ImageMetadata(imageStructure);

		// Emits the key-value pair
		context.write(keyStructure, imageMetadata);
	}

	/**
	 * Converts from bytesWritable to DICOM image.
	 * 
	 * @param dicomImage
	 * @return DICOM image
	 */
	private DICOM convertToDICOM(BytesWritable dicomImage) {
		byte[] inputContent = dicomImage.getBytes();

		InputStream inputStream = new ByteArrayInputStream(inputContent);

		DICOM convertedImage = new DICOM(inputStream);

		// Gives a generic name to the image file
		convertedImage.run("Dicom Image");

		return convertedImage;
	}

}
